### ISSUE TITLE
Difficulty in obtaining data sets

### ISSUE THREAD

**Issue by liyown** [AlexZaikin94/Proper-Face-Mask-Object-Detection#4]
I'm sorry to bother you，I cannot download the data set here, could you please tell me the format of the file after decompression, for example, it is full of pictures, or it is composed of several folders

**Comment by AlexZaikin94** [comment]
both datasets are organized differently in folders, you can see the structures on their pages:
https://www.kaggle.com/datasets/andrewmvd/face-mask-detection
https://www.kaggle.com/datasets/wobotintelligence/face-mask-detection-dataset

but eventually you have a folder of annotations and a folder of images.

it should be easy to get the data if you follow the instructions in the README.md

**Comment by liyown** [comment]
I see. Thank you very much for your reply
> 在 2022年5月29日，19:21，Alex Zaikin ***@***.***> 写道：
> 
> annotations
